### ISSUE TITLE
"Configure" option does not work on a Migrated Reality Toolkit project

### ISSUE THREAD

**Issue by SimonDarksideJ** [realitycollective/realitytoolkit.dev#51] opened 2022-09-04 10:26 UTC
# Reality Collective - Reality Toolkit Bug Report

## Describe the bug

In a project that has migrated from the Non-Service Framework version of the solution, the configure option does not add the toolkit configuration to an existing Service Framework configuration.

On diagnosis, this is simply because the asset files are not able to be copied to the project resulting in the following errors:

```
$Failed to copy asset!
C:\LocalDevelopment\00-xRealityLabs\Medtronic\MedtronicClient2021\Library\PackageCache\com.realitytoolkit.core@1.0.0-preview.6\Assets~\Profiles\InputSystem\DataProviders\HandControllers\Simulated\CommonInteractionMappingProfiles\YawCounterClockwiseProfile.asset.meta
C:\LocalDevelopment\00-xRealityLabs\Medtronic\MedtronicClient2021\Assets\RealityToolkit.Generated\Core\Profiles\InputSystem\DataProviders\HandControllers\Simulated\CommonInteractionMappingProfiles\YawCounterClockwiseProfile.asset.meta
UnityEngine.Debug:LogError (object)
RealityToolkit.Editor.PackageInstaller:CopyAsset (string,string,string) (at Library/PackageCache/com.realitytoolkit.core@1.0.0-preview.6/Editor/PackageInstaller.cs:216)
RealityToolkit.Editor.PackageInstaller:TryInstallAssets (System.Collections.Generic.Dictionary`2<string, string>,bool,bool) (at Library/PackageCache/com.realitytoolkit.core@1.0.0-preview.6/Editor/PackageInstaller.cs:101)
RealityToolkit.Editor.PackageInstaller:TryInstallAssets (string,string,bool,bool) (at Library/PackageCache/com.realitytoolkit.core@1.0.0-preview.6/Editor/PackageInstaller.cs:43)
RealityToolkit.Editor.CorePackageInstaller/<ConfigureToolkitAsync>d__5:MoveNext () (at Library/PackageCache/com.realitytoolkit.core@1.0.0-preview.6/Editor/CorePackageInstaller.cs:61)
System.Runtime.CompilerServices.AsyncVoidMethodBuilder:Start<RealityToolkit.Editor.CorePackageInstaller/<ConfigureToolkitAsync>d__5> (RealityToolkit.Editor.CorePackageInstaller/<ConfigureToolkitAsync>d__5&)
RealityToolkit.Editor.CorePackageInstaller:ConfigureToolkitAsync ()
```

## To Reproduce

1. Create a Non-Service Framework Reality Toolkit project and configure it
2. Also add the Service Framework to the project and add a Service Framework Instance
3. Update the Reality Toolkit to the Service Framework versions (latest, 0.6)
4. Run "Configure" again

## Expected behavior

Project should migrate and update to the latest service framework configuration

## Actual behavior

Lots of red in the console.

However, using the Core Platform Configurator asset does work

**Comment by FejZa** [comment] 2022-10-12 07:20
Closing this. There is no one out there using the "old" toolkit at this point except us two. So, there is no point in wasting time implementing migration tools. The issue is manually resolvable, let me know if you have issues migrating any of your projects.

**Closed as completed by FejZa** 2022-10-12 07:20 UTC
Labels: bug
